wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
gamma:
  desc: null
  value: 0.99
architecture:
  desc: null
  value: DQN
dataset_name:
  desc: null
  value: dataset_not_undefined
version:
  desc: null
  value: '0.1'
epochs:
  desc: null
  value: 10
n_history:
  desc: null
  value: 3
memory:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 64
target_update_freq:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717747517
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
